#!/usr/bin/env python3
"""Install this repository's Eval Flow into a project's Codex configuration."""
import argparse
import json
import shutil
import subprocess
from pathlib import Path


SOURCE = Path(__file__).resolve().parent
MARKER = "<!-- agent-workspace codex instructions -->"
CODEX_MODELS = {
    "code-writer": ("gpt-6-sol", "medium"),
    "code-reviewer": ("gpt-6-astra", "medium"),
    "task-verifier": ("gpt-6-luna", "high"),
    "task-decomposer": ("gpt-6-astra", "medium"),
    "usage-analyzer": ("gpt-6-astra", "low"),
    "impact-analyzer": ("gpt-6-astra", "low"),
    "retro": ("gpt-6-sol", "low"),
}


def add_agents_instructions(target):
    path = target / "AGENTS.md"
    block = f"""{MARKER}
## Eval Flow

For implementation requests, read `.agent-flow/ROUTER.md` before routing the task.
When the Router selects Tier 1, Tier 2, or B, load `.agents/skills/eval-flow/SKILL.md` and follow its state and evidence rules. For a bug, diagnose before routing; for an interrupted run, load `.agents/skills/eval-flow-resume/SKILL.md`.
Read `.agent-flow/CODEX_ADAPTER.md` whenever a flow instruction names Claude Code tools, agents, permissions, or worktree behavior.
For each new Codex run, set manifest `harness: "codex"` and `evidence_schema: 2` (Tier 1/2). Use `run_verify.py` for the final full-suite command. After commit, run `run_commit.py finalize <run_id>`.
Use the matching project Codex agents for delegated roles. Record a named question when asking an advisor. The user request and applicable higher-priority instructions take precedence over the workflow.
<!-- /agent-workspace codex instructions -->"""
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        start = existing.find(MARKER)
        if start >= 0:
            end_marker = "<!-- /agent-workspace codex instructions -->"
            end = existing.find(end_marker, start)
            if end < 0:
                raise ValueError(f"{path} has an unterminated managed section")
            end += len(end_marker)
            path.write_text(existing[:start] + block + existing[end:], encoding="utf-8")
            return
        path.write_text(existing.rstrip() + "\n\n" + block + "\n", encoding="utf-8")
    else:
        path.write_text(block + "\n", encoding="utf-8")


def toml_string(value):
    return json.dumps(value, ensure_ascii=False)


def install_agents(target):
    destination = target / ".codex" / "agents"
    destination.mkdir(parents=True, exist_ok=True)
    for path in sorted((SOURCE / ".claude" / "agents").glob("*.md")):
        source = path.read_text(encoding="utf-8")
        pieces = source.split("---", 2)
        body = pieces[2].strip() if len(pieces) == 3 else source
        body = (body.replace("CLAUDE.md", ".agent-flow/ROUTER.md")
                    .replace("skills/", ".agents/skills/"))
        body = "Codex role adapter: use Codex tools that match the tool names in this role.\n\n" + body
        name = path.stem
        description = next((line.strip() for line in pieces[1].splitlines() if line.startswith("  ")), name) if len(pieces) == 3 else name
        content = (
            "# Generated by agent_workspace/install_codex.py\n"
            f"name = {toml_string(name)}\n"
            f"description = {toml_string(description)}\n"
            f"model = {toml_string(CODEX_MODELS[name][0])}\n"
            f"model_reasoning_effort = {toml_string(CODEX_MODELS[name][1])}\n"
            f"developer_instructions = {toml_string(body)}\n"
        )
        output = destination / f"{name}.toml"
        if output.exists() and not output.read_text(encoding="utf-8").startswith("# Generated by agent_workspace/"):
            print(f"[codex] preserved custom agent: {output}")
            continue
        output.write_text(content, encoding="utf-8")


def install_hooks(target):
    path = target / ".codex" / "hooks.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    data = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {"hooks": {}}
    hooks = data.setdefault("hooks", {})
    command = 'python3 "$(git rev-parse --show-toplevel)/.claude/hooks/eval_gates.py" --hook'
    entry = {"matcher": "Bash|Agent", "hooks": [{"type": "command", "command": command, "timeout": 30}]}
    if entry not in hooks.setdefault("PreToolUse", []):
        hooks["PreToolUse"].append(entry)
    session_command = 'python3 "$(git rev-parse --show-toplevel)/.claude/hooks/session_start.py"'
    session_entry = {"matcher": "startup|resume|compact", "hooks": [{"type": "command", "command": session_command, "timeout": 15}]}
    if session_entry not in hooks.setdefault("SessionStart", []):
        hooks["SessionStart"].append(session_entry)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def install_git_hook(target):
    result = subprocess.run(["git", "-C", str(target), "config", "--get", "core.hooksPath"], capture_output=True, text=True)
    if result.returncode == 0:
        print(f"[codex] existing core.hooksPath={result.stdout.strip()}; add commit_message_gate.py to that commit-msg hook")
        return
    result = subprocess.run(["git", "-C", str(target), "rev-parse", "--git-path", "hooks/commit-msg"], capture_output=True, text=True)
    if result.returncode != 0:
        print("[codex] target is not a Git repository; commit-msg hook not installed")
        return
    path = Path(result.stdout.strip())
    if not path.is_absolute():
        path = target / path
    if path.exists():
        if "agent-workspace" not in path.read_text(encoding="utf-8", errors="replace"):
            print(f"[codex] preserved existing commit-msg hook: {path}")
            return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        '#!/bin/sh\n# agent-workspace managed commit message gate\n'
        'exec python3 "$(git rev-parse --show-toplevel)/.claude/hooks/commit_message_gate.py" "$1"\n',
        encoding="utf-8",
    )
    path.chmod(0o755)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", type=Path, default=SOURCE.parent)
    parser.add_argument("--git-hook-only", action="store_true")
    args = parser.parse_args()
    target = args.target.resolve()
    target.mkdir(parents=True, exist_ok=True)
    if args.git_hook_only:
        install_git_hook(target)
        return
    router = target / ".agent-flow" / "ROUTER.md"
    router.parent.mkdir(parents=True, exist_ok=True)
    if router.exists() and not router.read_text(encoding="utf-8").startswith("<!-- agent-workspace managed -->"):
        raise ValueError(f"preserving custom router: {router}")
    router_body = (SOURCE / "CLAUDE.md").read_text(encoding="utf-8")
    router_body = router_body.replace("# CLAUDE.md", "# Eval Flow Router", 1).replace("skills/", ".agents/skills/")
    router.write_text("<!-- agent-workspace managed -->\n" + router_body, encoding="utf-8")
    model_policy = target / ".agent-flow" / "CODEX_MODEL_POLICY.md"
    model_policy.write_text(
        "<!-- agent-workspace managed -->\n# Codex model policy\n\n"
        "Writer and reviewer use different GPT-6 models for independent review.\n\n"
        "| Role | Model | Reasoning effort |\n|---|---|---|\n"
        + "".join(f"| {role} | {model} | {effort} |\n" for role, (model, effort) in CODEX_MODELS.items()),
        encoding="utf-8",
    )
    adapter = target / ".agent-flow" / "CODEX_ADAPTER.md"
    if adapter.exists() and not adapter.read_text(encoding="utf-8").startswith("<!-- agent-workspace managed -->"):
        raise ValueError(f"preserving custom adapter: {adapter}")
    adapter.write_text("<!-- agent-workspace managed -->\n" + (SOURCE / "CODEX_ADAPTER.md").read_text(encoding="utf-8"), encoding="utf-8")
    hooks_dir = target / ".claude" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    for path in (SOURCE / ".claude" / "hooks").glob("*.py"):
        destination = hooks_dir / path.name
        if path.resolve() != destination.resolve():
            shutil.copy2(path, destination)
    version_source = SOURCE / ".claude" / "hooks" / "VERSION"
    version_target = hooks_dir / "VERSION"
    if version_source.resolve() != version_target.resolve():
        shutil.copy2(version_source, version_target)
    retro_dir = target / "retro"
    retro_dir.mkdir(parents=True, exist_ok=True)
    retro = retro_dir / "RETRO.md"
    if not retro.exists():
        shutil.copy2(SOURCE / "seed" / "RETRO.seed.md", retro)
    buglog = retro_dir / "BUGLOG.md"
    if not buglog.exists():
        source_buglog = (SOURCE / "retro" / "BUGLOG.md").read_text(encoding="utf-8")
        header, separator, _ = source_buglog.partition("\n---\n")
        if not separator:
            raise ValueError("source BUGLOG.md lacks the header separator")
        buglog.write_text(header + separator, encoding="utf-8")
    skills_root = target / ".agents" / "skills"
    skills_root.mkdir(parents=True, exist_ok=True)
    source_skill_names = {skill.name for skill in (SOURCE / "skills").iterdir() if skill.is_dir() and skill.name != "_deprecated"}
    for destination in skills_root.iterdir():
        if destination.is_dir() and destination.name not in source_skill_names and (destination / ".agent-workspace-managed").exists():
            shutil.rmtree(destination)
    for skill in (SOURCE / "skills").iterdir():
        if not skill.is_dir() or skill.name == "_deprecated":
            continue
        destination = target / ".agents" / "skills" / skill.name
        if destination.exists():
            if not (destination / ".agent-workspace-managed").exists():
                print(f"[codex] preserved custom skill: {destination}")
                continue
            shutil.rmtree(destination)
        shutil.copytree(skill, destination)
        (destination / ".agent-workspace-managed").write_text("managed by agent_workspace\n", encoding="utf-8")
        for md in destination.rglob("*.md"):
            text = md.read_text(encoding="utf-8")
            md.write_text(text.replace("CLAUDE.md", ".agent-flow/ROUTER.md")
                              .replace("skills/", ".agents/skills/"), encoding="utf-8")
    add_agents_instructions(target)
    install_agents(target)
    install_hooks(target)
    install_git_hook(target)
    print(f"[codex] installed Eval Flow in {target}")


if __name__ == "__main__":
    main()
